### PR TITLE
Update Readme to Close Specs Repo

### PR DESCRIPTION
**Pull request by trianglesphere**
End of an era.

Fixes ENG-2231

### CODE REVIEW

**Comment by maurelian** [comment]
wait until we've got the OZ audit fixes in please.

**Comment by trianglesphere** [comment]
> wait until we've got the OZ audit fixes in please.

Would we be able to merge this prior to actually archiving the repo?

**Comment by maurelian** [comment]
@trianglesphere oh yeah, that's fine with me.

**Review by maurelian — APPROVED** [review]
LGTM

**Comment by maurelian** [comment]
Merging despite broken CI in order to ensure visitors are properly directed to the Monorepo.

**Pull request merged**
